### ISSUE TITLE
Major change: auto-generate bsp code

### ISSUE THREAD

**Issue by T-K-233** [ucb-bar/Baremetal-IDE-bsp#16]
Currently, we are maintaining 4 chip bsp libraries, in which almost all of the contents are the same. Any bug fix or new feature needs to be synced across all bsp folders, which does not quite make sense.

Instead, the new method is proposed, where we use Python to auto generate bsp codes from a set of template library files. Considering the amount of code needed, this major change can be implemented in several stages:

1. Be able to generate HAL_<peripheral> library files from a set of template files. The Python program will read library files from the template folder, create a bsp folder, and write the library files to the created bsp folder with proper formatting (e.g. rename the file to include chipname)

2. Be able to generate chip header file (chipname.h) from the chip configuration JSON file. The JSON file will be very similar to the .svd file used by the VSCode debugging environment. It will contain the memory map of the SoC, register map of each peripheral, and the bit map of each peripheral register.

3. Be able to generate the chip configuration JSON file during Chipyard compilation.

**Comment by ethanwu10** [comment]
For the actual HAL code, I think it would be better to build a single shared library and then link against it from each board's BSP, and only generate a header file containing info about what peripheral is at what address. I don't really like the idea of generating actual library source code, since then we'd lose good IDE support on editing the library implementations.

To deal with differing hardware revisions, we should probably `#ifdef` hardware-specific portions and set configuration flags during compilation.

**Comment by T-K-233** [comment]
I think a valid approach is this:

under `/bsp/common`, we store the files for common periphery devices, like CORE, UART, GPIO etc.. If the SoC has custom periphery devices, it will be stored under `/bsp/<chipname>`, but still with name `hal_<peripheryname>.h` and `hal_<peripheryname>.h`. 

For the main `hal.h` and `hal.c`, it should be moved into user program, under `/core`. Reasons being: 

1. In `hal.h` we will define settings like the system clock frequency, clock tree muxes etc. This is application-dependent, and therefore should be controlled by user.
2. The `HAL_init()` routine will also differ by chips, and therefore should be put in `/core/hal.c`, and user can modify the init routine.
3. `hal.h` controls which peripheral devices are included in the final program. To reduce code size, user can exclude the code for unused periphery devices.

As a result, in `/core/inc/main.h`, user will do

```c
#include "hal.h"
```

and in `/core/inc/hal.h`, it will be

```c
#include "<chipname>.h"

#include "hal_core.h"
#include "hal_clint.h"
#include "hal_gpio.h"
#include "hal_i2c.h"
...

#define HXTAL_FREQ     20000000                   // Hz
// #define HXTAL_FREQ    100000000                   // Hz
#define SYS_CLK_FREQ  HXTAL_FREQ / 2              // Hz
#define MTIME_FREQ    (SYS_CLK_FREQ / 100000)     // tick per milliseconds

```
